language: cpp

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

osx_image: xcode9.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-add-repository 'deb http://repos.codelite.org/wx3.1.0/ubuntu/ zesty universe' -qq; sudo apt-get update -qq; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 30 brew install wxwidgets; brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libwxbase3.1-0-unofficial libwxbase3.1-dev libwxgtk3.1-0-unofficial libwxgtk3.1-dev wx3.1-headers wx-common libwxgtk-webview3.1-0-unofficial libwxgtk-webview3.1-dev libwxgtk-media3.1-0-unofficial libwxgtk-media3.1-dev libwxbase3.1-0-unofficial-dbg libwxgtk3.1-0-unofficial-dbg libwxgtk-webview3.1-0-unofficial-dbg libwxgtk-media3.1-0-unofficial-dbg wx3.1-i18n wx3.1-examples -qq; fi

before_script:
  - cd C++
  - mkdir build
  - cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake .. -G "Xcode"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cmake ..; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcodebuild -target GooCore -project GooCore.xcodeproj; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make; fi

deploy:
  provider: releases
  api_key:
    secure: KTRASG0NaxHTKXV3KQ5Ux+PJMJdcr6tBov5TkrkrYCYxfSpOC5cB1tWSrkdM48zRDJKQVfbOSPbtHlIPcFRB5+jnUYUz7h4ynDwBprM83cxpgzt8itgBr1w4XjnDDlU+0FgVkz63W2TxltMq5hMxhWkbVr3+NLU07h/Hk3YMP1d19y9jBMYgjeqQeBOf3LCvaSZU/A7+NsBOaNn/aLkgTvoxkfsJ/xPCWYVNpTwE/f+y2QVzN0eV4V8LEFAr7p7REY5FaQyvn2n1b4hGPla4ZNuRHQT6v158BTMj7r6KMqVUlFk6wYFmfstBJq8nHBSwt+NlfeDIBI526+m7bkucCkjmxNR3O8voiLbsSgkm0Je/M7mQUofGfGI5x/KaLtLv+ZNmTHhMyX4Iah9BfF/1g38Z16qVZ1mDrnHR2rvC/bOKbJqQAmoWu+9MvaiLfUqGJAoLJHwZIQN/kv+/9a6HpSTiEaZ+Rgo3cSKhGOsnoUxroATERG9mPsw8qin53MhmH0lBG9Mh1Nrb+mI49SRe1AhLiqKZnfsMcuCUE6nZWfS2/HHLYOP+BaeydKzBfjfz3lbC81+izxa85+Dog0ST7USWE28BNSxuezodfUZcmI9/Dgmt2JguNctW0TcikfM1dP1aId7UUW3GQhRqHxQvuZ2BV+MXTdvJTRiLijP42uk=
  skip_cleanup: true
  file: Debug/libGooCore.dylib
  on:
    repo: GooborgStudios/GooCore
    tags: true
